BEGIN TRY

    BEGIN TRAN

USE [Production_Management_System]


IF EXISTS (SELECT  1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='Crop_Details')
DROP TABLE [dbo].[Crop_Details]

IF EXISTS (SELECT  1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='Employee_Details')
DROP TABLE [dbo].[Employee_Details]

IF EXISTS (SELECT  1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='Employee_Shedule')
DROP TABLE [dbo].[Employee_Shedule]

IF EXISTS (SELECT  1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='Machine_Details')
DROP TABLE [dbo].[Machine_Details]

IF EXISTS (SELECT  1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='Machine_Shedule')
DROP TABLE [dbo].[Machine_Shedule]

IF EXISTS (SELECT  1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='Process_Details')
DROP TABLE [dbo].[dbo].[Process_Details]

IF EXISTS (SELECT  1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='Process_Shedule')
DROP TABLE [dbo].[Process_Shedule]

IF EXISTS (SELECT  1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='Supplier_Details') 
DROP TABLE [dbo].[Supplier_Details]

IF EXISTS (SELECT  1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='UserProfile') 
DROP TABLE [dbo].[UserProfile]

IF EXISTS (SELECT  1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='webpages_OAuthMembership') 
DROP TABLE [dbo].[webpages_OAuthMembership]

IF EXISTS (SELECT  1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='webpages_Membership') 
DROP TABLE [dbo].[webpages_Membership]

IF EXISTS (SELECT  1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='webpages_Roles') 
DROP TABLE [dbo].[webpages_Roles]

IF EXISTS (SELECT  1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='webpages_UsersInRoles') 
DROP TABLE [dbo].[webpages_UsersInRoles]

 COMMIT TRAN

END TRY

BEGIN CATCH

ROLLBACK TRAN
SELECT ERROR_MESSAGE()

END CATCH